CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(60) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_app_users_first_name_not_blank CHECK (TRIM(first_name) <> ''),
    CONSTRAINT ck_app_users_last_name_not_blank CHECK (TRIM(last_name) <> ''),
    CONSTRAINT ck_app_users_email_not_blank CHECK (TRIM(email) <> ''),
    CONSTRAINT ck_app_users_email_normalized CHECK (email = LOWER(TRIM(email))),
    CONSTRAINT uk_app_users_email UNIQUE (email)
);
