CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    normalized_name VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    deactivated_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_categories_normalized_name UNIQUE (normalized_name),
    CONSTRAINT ck_categories_name_not_blank CHECK (TRIM(name) <> ''),
    CONSTRAINT ck_categories_normalized_name CHECK (normalized_name = LOWER(TRIM(name))),
    CONSTRAINT ck_categories_archive_state CHECK (
        (active = TRUE AND deactivated_at IS NULL)
        OR (active = FALSE AND deactivated_at IS NOT NULL)
    )
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(80) NOT NULL,
    normalized_sku VARCHAR(80) NOT NULL,
    name VARCHAR(180) NOT NULL,
    category_id BIGINT NOT NULL,
    unit_of_measure VARCHAR(30) NOT NULL,
    purchase_price NUMERIC(19, 2) NOT NULL,
    selling_price NUMERIC(19, 2) NOT NULL,
    current_stock BIGINT NOT NULL DEFAULT 0,
    minimum_stock BIGINT NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    deactivated_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT uk_products_normalized_sku UNIQUE (normalized_sku),
    CONSTRAINT ck_products_sku_not_blank CHECK (TRIM(sku) <> ''),
    CONSTRAINT ck_products_normalized_sku CHECK (normalized_sku = UPPER(TRIM(sku))),
    CONSTRAINT ck_products_name_not_blank CHECK (TRIM(name) <> ''),
    CONSTRAINT ck_products_unit CHECK (unit_of_measure IN ('PIECE', 'BOX', 'PACK')),
    CONSTRAINT ck_products_purchase_price CHECK (purchase_price >= 0),
    CONSTRAINT ck_products_selling_price CHECK (selling_price >= 0),
    CONSTRAINT ck_products_current_stock CHECK (current_stock >= 0),
    CONSTRAINT ck_products_minimum_stock CHECK (minimum_stock >= 0),
    CONSTRAINT ck_products_archive_state CHECK (
        (active = TRUE AND deactivated_at IS NULL)
        OR (active = FALSE AND deactivated_at IS NOT NULL)
    )
);

CREATE INDEX idx_products_category ON products (category_id);
CREATE INDEX idx_products_active_name ON products (active, name);
