CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(180) NOT NULL,
    ice VARCHAR(30),
    contact_person VARCHAR(180),
    email VARCHAR(254),
    phone VARCHAR(30),
    address VARCHAR(500),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    deactivated_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_customers_name_not_blank CHECK (TRIM(name) <> ''),
    CONSTRAINT ck_customers_email_normalized CHECK (email IS NULL OR email = LOWER(TRIM(email))),
    CONSTRAINT ck_customers_archive_state CHECK (
        (active = TRUE AND deactivated_at IS NULL)
        OR (active = FALSE AND deactivated_at IS NOT NULL)
    )
);

CREATE TABLE suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(180) NOT NULL,
    ice VARCHAR(30),
    contact_person VARCHAR(180),
    email VARCHAR(254),
    phone VARCHAR(30),
    address VARCHAR(500),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    deactivated_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_suppliers_name_not_blank CHECK (TRIM(name) <> ''),
    CONSTRAINT ck_suppliers_email_normalized CHECK (email IS NULL OR email = LOWER(TRIM(email))),
    CONSTRAINT ck_suppliers_archive_state CHECK (
        (active = TRUE AND deactivated_at IS NULL)
        OR (active = FALSE AND deactivated_at IS NOT NULL)
    )
);

CREATE INDEX idx_customers_active_name ON customers (active, name);
CREATE INDEX idx_suppliers_active_name ON suppliers (active, name);
