CREATE TABLE stock_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    movement_type VARCHAR(30) NOT NULL,
    quantity_delta BIGINT NOT NULL,
    stock_before BIGINT NOT NULL,
    stock_after BIGINT NOT NULL,
    reference VARCHAR(120) NOT NULL,
    reason VARCHAR(180) NOT NULL,
    note VARCHAR(1000),
    created_by_user_id BIGINT NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_stock_movements_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_stock_movements_user FOREIGN KEY (created_by_user_id) REFERENCES app_users (id),
    CONSTRAINT ck_stock_movements_type CHECK (
        movement_type IN ('STOCK_IN', 'STOCK_OUT', 'ADJUSTMENT', 'RESTORE')
    ),
    CONSTRAINT ck_stock_movements_delta_non_zero CHECK (quantity_delta <> 0),
    CONSTRAINT ck_stock_movements_balances_non_negative CHECK (stock_before >= 0 AND stock_after >= 0),
    CONSTRAINT ck_stock_movements_balance CHECK (stock_after = stock_before + quantity_delta),
    CONSTRAINT ck_stock_movements_direction CHECK (
        (movement_type IN ('STOCK_IN', 'RESTORE') AND quantity_delta > 0)
        OR (movement_type = 'STOCK_OUT' AND quantity_delta < 0)
        OR movement_type = 'ADJUSTMENT'
    ),
    CONSTRAINT ck_stock_movements_reference_not_blank CHECK (TRIM(reference) <> ''),
    CONSTRAINT ck_stock_movements_reason_not_blank CHECK (TRIM(reason) <> '')
);

CREATE INDEX idx_stock_movements_product_occurred
    ON stock_movements (product_id, occurred_at DESC);
CREATE INDEX idx_stock_movements_type_occurred
    ON stock_movements (movement_type, occurred_at DESC);
CREATE INDEX idx_stock_movements_created_by
    ON stock_movements (created_by_user_id);
