CREATE SEQUENCE sales_order_number_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE sales_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(40) NOT NULL,
    customer_id BIGINT NOT NULL,
    order_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    subtotal NUMERIC(19, 2) NOT NULL,
    discount_amount NUMERIC(19, 2) NOT NULL DEFAULT 0,
    tax_amount NUMERIC(19, 2) NOT NULL,
    total_amount NUMERIC(19, 2) NOT NULL,
    note VARCHAR(1000),
    confirmed_at TIMESTAMP WITH TIME ZONE,
    delivered_at TIMESTAMP WITH TIME ZONE,
    created_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_sales_orders_number UNIQUE (order_number),
    CONSTRAINT fk_sales_orders_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT fk_sales_orders_user FOREIGN KEY (created_by_user_id) REFERENCES app_users (id),
    CONSTRAINT ck_sales_orders_status CHECK (status IN ('DRAFT', 'CONFIRMED', 'DELIVERED', 'CANCELLED')),
    CONSTRAINT ck_sales_orders_amounts CHECK (
        subtotal >= 0 AND discount_amount >= 0 AND discount_amount <= subtotal
        AND tax_amount >= 0 AND total_amount = subtotal - discount_amount + tax_amount
    ),
    CONSTRAINT ck_sales_orders_timestamps CHECK (
        (status IN ('DRAFT', 'CANCELLED') AND confirmed_at IS NULL AND delivered_at IS NULL)
        OR (status = 'CONFIRMED' AND confirmed_at IS NOT NULL AND delivered_at IS NULL)
        OR (status = 'DELIVERED' AND confirmed_at IS NOT NULL AND delivered_at IS NOT NULL)
    )
);

CREATE TABLE sales_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity BIGINT NOT NULL,
    unit_price NUMERIC(19, 2) NOT NULL,
    tax_rate NUMERIC(5, 2) NOT NULL,
    line_subtotal NUMERIC(19, 2) NOT NULL,
    line_tax NUMERIC(19, 2) NOT NULL,
    line_total NUMERIC(19, 2) NOT NULL,
    CONSTRAINT fk_sales_order_items_order FOREIGN KEY (sales_order_id) REFERENCES sales_orders (id),
    CONSTRAINT fk_sales_order_items_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT uk_sales_order_items_product UNIQUE (sales_order_id, product_id),
    CONSTRAINT ck_sales_order_items_quantity CHECK (quantity > 0),
    CONSTRAINT ck_sales_order_items_money CHECK (
        unit_price >= 0 AND tax_rate >= 0 AND tax_rate <= 100
        AND line_subtotal >= 0 AND line_tax >= 0 AND line_total = line_subtotal + line_tax
    )
);

ALTER TABLE stock_movements ADD COLUMN sales_order_item_id BIGINT;
ALTER TABLE stock_movements ADD CONSTRAINT fk_stock_movements_sales_item
    FOREIGN KEY (sales_order_item_id) REFERENCES sales_order_items (id);
CREATE UNIQUE INDEX uk_stock_movements_sales_item ON stock_movements (sales_order_item_id);

CREATE INDEX idx_sales_orders_customer ON sales_orders (customer_id);
CREATE INDEX idx_sales_orders_status_date ON sales_orders (status, order_date DESC);
CREATE INDEX idx_sales_orders_order_date ON sales_orders (order_date DESC);
CREATE INDEX idx_sales_order_items_product ON sales_order_items (product_id);
